const POLISH: Record<string, string> = {
  Name: "Imię i nazwisko",
  "Contact details": "Dane kontaktowe",
  Summary: "Podsumowanie",
  Experience: "Doświadczenie",
  Education: "Wykształcenie",
  Skills: "Umiejętności",
  Languages: "Języki",
  Courses: "Kursy",
  Interests: "Zainteresowania",
  "First name": "Imię",
  "Family name": "Nazwisko",
  "Auto-generate brand initials": "Twórz inicjały automatycznie",
  Location: "Lokalizacja",
  Phone: "Telefon",
  "E-mail": "E-mail",
  LinkedIn: "LinkedIn",
  Portfolio: "Portfolio",
  Position: "Stanowisko",
  Description: "Opis",
  "Default summary": "Domyślne podsumowanie",
  Default: "Domyślne",
  "Summary description": "Treść podsumowania",
  "Remove entry": "Usuń wpis",
  "+ Add summary": "+ Dodaj podsumowanie",
  "Untitled summary": "Nowe podsumowanie",
  Label: "Etykieta",
  "Image path": "Ścieżka obrazu",
  Size: "Rozmiar",
  Remove: "Usuń",
  "+ Add QR code": "+ Dodaj kod QR",
  Skill: "Umiejętność",
  Level: "Poziom",
  "+ Add skill": "+ Dodaj umiejętność",
  Technology: "Technologia",
  "+ Add technology": "+ Dodaj technologię",
  Language: "Język",
  "Level text": "Opis poziomu",
  "+ Add language": "+ Dodaj język",
  Interest: "Zainteresowanie",
  "+ Add interest": "+ Dodaj zainteresowanie",
  "Untitled role": "Nowe stanowisko",
  Period: "Okres",
  Company: "Firma",
  Role: "Stanowisko",
  "Highlights, one per line": "Osiągnięcia, każde w osobnej linii",
  "+ Add position": "+ Dodaj stanowisko",
  "Untitled school": "Nowa szkoła",
  School: "Szkoła lub uczelnia",
  Degree: "Tytuł lub stopień",
  Detail: "Szczegóły",
  "+ Add education": "+ Dodaj wykształcenie",
  Year: "Rok",
  "Course name": "Nazwa kursu",
  "+ Add course": "+ Dodaj kurs",
  "Clause text": "Treść klauzuli",
  "No clause": "Brak klauzuli",
  "Use standard PL wording": "Wstaw standardową polską klauzulę",
  Clear: "Wyczyść",
  "Rendered as a small footer on the CV. Leave empty to omit it.":
    "Klauzula pojawi się w stopce CV. Pozostaw puste pole, aby ją pominąć."
};

export function onboardingEditorText(text: string, language: "en" | "pl"): string {
  return language === "pl" ? (POLISH[text] ?? text) : text;
}
